In [2]:
import torch

In [5]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [10]:
y = torch.arange(2, 10, dtype=torch.float32)
y

tensor([2., 3., 4., 5., 6., 7., 8., 9.])

In [13]:
y.numel()

8

In [14]:
x.numel()

12

In [17]:
X = x.reshape(1, 1, 1, 6, 2)
X

tensor([[[[[ 0.,  1.],
           [ 2.,  3.],
           [ 4.,  5.],
           [ 6.,  7.],
           [ 8.,  9.],
           [10., 11.]]]]])

In [22]:
Y = y.reshape(2, 2, 2)
Y

tensor([[[2., 3.],
         [4., 5.]],

        [[6., 7.],
         [8., 9.]]])

In [23]:
Y1 = y.reshape(-1, 4)
Y1

tensor([[2., 3., 4., 5.],
        [6., 7., 8., 9.]])

In [25]:
torch.zeros((2, 3, 5, 2))

tensor([[[[0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.]]]])

In [26]:
torch.ones((2, 2, 2))

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [27]:
torch.randn(2, 3, 3) #randn -> values from a standard Gaussian distribution with mean 0 and s.d. 1

tensor([[[ 0.6055, -1.2779, -0.8545],
         [-0.0573, -1.1017,  0.1090],
         [ 0.5854, -0.1029, -0.0905]],

        [[ 1.4341,  0.6942, -0.2544],
         [ 0.7426,  0.2490,  0.6212],
         [ 0.8545, -1.3022, -1.1313]]])

In [29]:
X = x.reshape(4, 3)
X[-1]

tensor([ 9., 10., 11.])

In [31]:
X[0:3]

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [32]:
Y.ndim

3

In [34]:
Y = y.reshape(4, 2)
Y.ndim

2

In [35]:
Y

tensor([[2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])

In [36]:
X

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [37]:
X[1, 2] = 17

In [39]:
X

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., 17.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [40]:
X[:1, 1] = 10

In [41]:
X

tensor([[ 0., 10.,  2.],
        [ 3.,  4., 17.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [42]:
X[:4, 2] = 7

In [43]:
X

tensor([[ 0., 10.,  7.],
        [ 3.,  4.,  7.],
        [ 6.,  7.,  7.],
        [ 9., 10.,  7.]])

In [44]:
torch.exp(X)

tensor([[1.0000e+00, 2.2026e+04, 1.0966e+03],
        [2.0086e+01, 5.4598e+01, 1.0966e+03],
        [4.0343e+02, 1.0966e+03, 1.0966e+03],
        [8.1031e+03, 2.2026e+04, 1.0966e+03]])